# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-13 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_cluster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wine',
            new_name='Food',
        ),
    ]
